name: diary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.2.0
  path_provider: ^2.1.4
  path: ^1.9.0  
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  table_calendar: ^3.0.9
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/data/
    - assets/image/
